name = 'edgetunnel'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"        # KV binding name, must not be changed
id = "cf69fe7bcc854241b93da52a2c054069"        # KV namespace ID
